object Versions {
    const val gradlePlugin = "7.0.3"
    const val kotlin = "1.6.0"
    const val roomVersion = "2.3.0"
    const val navigation = "2.4.0-beta02"
    const val arrow = "1.0.1"
    const val hilt = "2.38.1"
    const val ktx = "1.7.0"
    const val fragmentKtx = "1.3.6"
    const val androidLifeCycleExt = "2.2.0"
    const val coroutine = "1.3.9"
    const val androidCoroutine = "1.5.1"
    const val retrofit = "2.9.0"
    const val retrofitCoroutineAdapter = "0.9.2"
    const val appCompat = "1.4.0"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.2"
    const val jUnit = "4.12"
    const val mockk = "1.12.0"
    const val kotest = "4.4.3"
    const val archCoreTest = "2.1.0"
    const val androidJUnit = "1.1.3"
    const val espresso = "3.4.0"
}